---
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes
    
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes
    - name: Install Python, Node, NPM
      become: true
      apt:
        name: ["npm", "nodejs", "python3", "tar", "gzip"]
    - name: Install pm 2
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
    - name: Adding the path in the bashrc files for env variabels
      blockinfile:
        path: ~/.bashrc
        insertafter: 'EOF'
        state: present 
        block: |
         export ENVIRONMENT=production
         export NODE_ENV=production
         export NODE_PORT=3030
         export TYPEORM_CONNECTION=postgres
         export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
         export TYPEORM_HOST={{ lookup('env','TYPEORM_HOST') }}
         export TYPEORM_PORT={{ lookup('env','TYPEORM_PORT') }}
         export TYPEORM_USERNAME={{ lookup('env','TYPEORM_USERNAME') }}
         export TYPEORM_PASSWORD={{ lookup('env','TYPEORM_PASSWORD') }}
         export TYPEORM_DATABASE={{ lookup('env','TYPEORM_DATABASE') }}
         export TYPEORM_PORT=5432
         export VERSION=1
         export PORT=3030