---
    - name: Copy over app,
      become: true
      copy:
        # Uncomment to run remotely on circleci src: /home/circleci/project/backend/.dist
        src: /root/project/backend.tar.gz
        dest: /home/ubuntu/backend.tar.gz
    - name: Unzip the backend
      become: true
      shell: |
        cd /home/ubuntu/
        mkdir backend
        tar -C backend -xvf backend.tar.gz
        cd backend
        npm i
        npm audit fix --audit-level=critical --force
        npm run build
    - name: start the pm2 server
      become: true
      shell: |
        cd /home/ubuntu/backend
        pm2 start "npm start" --name backend