---
    - name: Copy over app,
      copy:
        # Uncomment to run remotely on circleci src: /home/circleci/project/backend/.dist
        src: /root/project/backend/dist
        dest: /home/ubuntu/app
    - name: start the pm2 server
      become: true
      shell: |
        cd /home/ubuntu/app
        pm2 start dist/main.js -- --port 3030